### ISSUE TITLE
build error error: cannot find symbol @Ignore

### ISSUE THREAD

**Issue by Sairapp** [mauron85/react-native-background-geolocation#389]
## Your Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 61.61 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.3
        System Images: android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Pla
y Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Goo
gle Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.5 => 16.8.5 
      react-native: ^0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

* Plugin version: 0.5.3
* Platform: Android
* OS version: macOs Mojave version 10.14.3
* Device manufacturer and model:

* Running in Simulator: yes
* React Native version: 0.59.5

## Context

after installed the lib, i linked it manually
tried to run 
` ./gradlew clean --info && ./gradlew build --info `
## Expected Behavior

i expected build will run successfully
## Actual Behavior

build error

## Possible Fix
seems error came from tests, i tried to comment @ ignore but got more issues

## Steps to Reproduce

1. installed the lib ` yarn add  @mauron85/react-native-background-geolocation`
2. linked it manually following the [README](https://github.com/mauron85/react-native-background-geolocation/blob/master/README.md)
3. clean & build the gradle ` ./gradlew clean --info && ./gradlew build --info `

## Context

i can't build the project in android platform

## Debug logs

````
/Users/mac/Documents/SAIR/driver/node_modules/@mauron85/react-native-background-geolocation/android/lib/src/test/java/com/marianhello/bgloc/react/ConfigMapperTest.java:59: error: cannot find symbol
    @Ignore
     ^
  symbol:   class Ignore
  location: class ConfigMapperTest
Note: /Users/mac/Documents/SAIR/driver/node_modules/@mauron85/react-native-background-geolocation/android/lib/src/test/java/com/marianhello/bgloc/react/ConfigMapperTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
````

**Comment by bilsak18** [comment]
I'm struggling with these kinda errors too after that my app was working properly.
I guess it has something to do with the release of the new react-native version **0.60.0** and the changes it brought with it.

**Comment by wesleycoder** [comment]
This error also occurs on react-native 0.59.9.
I found that some test files are missing the import for the `@Ignore` from java test utils.

**Comment by wesleycoder** [comment]
I didn't made a PR yet because after placing the missing `@Ignore` import in place I got stuck onto other issues that seems to be unrelated but I'm not sure yet.

**Comment by jagaa1103** [comment]
Me too. And I'm imported @Ignore on Android Studio and it's works.

**Comment by a-eid** [comment]
Facing same issue on `react-native: 59.2`

**Comment by prasan2421** [comment]
got the same issue on version 0.60.4, any solution??

**Comment by DanDance** [comment]
importing Ignore solved `cannot find symbol @Ignore`, but now I have issues with importing `SmallTest` in tests files. Also found weird behaviour. App builds on Emulator Android 8.0.0, but fails to run on real device with 4.4.2. Not sure how it works... Looking for solutions
