### ISSUE TITLE
Issue #318 still present

### ISSUE THREAD

**Issue by DGCarramona** [mauron85/react-native-background-geolocation#516]
## Your Environment
* Plugin version: v0.5.3
* Platform: iOS
* OS version: 14
* Device manufacturer and model: iPhone 11

* Running in Simulator: yes
* React Native version: 0.63.3
* Plugin configuration options: default
* Link to your project: private project

## Context
Which info do you need ?

## Expected Behavior
Application built without error

## Actual Behavior
Link error with "duplicate symbols for architecture x86_64

## Steps to Reproduce
Just followed installation steps in README

**Comment by DGCarramona** [comment]
Forgot to mention, issue reappeared after upgrading react-native from 0.61 to 0.63.3

**Comment by iamsteeve** [comment]
Xo

**Comment by SergioPereo** [comment]
> Forgot to mention, issue reappeared after upgrading react-native from 0.61 to 0.63.3
Any workaround so far? Or I should give a try to another library?

**Comment by Rc85** [comment]
Current workaround:

1. Click on `Pods` and open `Pods-[your-project-name].release` and `Pods-[your-project-name].debug`
2. Scroll down to `OTHER_LDFLAGS`
3. Delete `-ObjC -l "@mauron/react-native-background-geolocation"` (might have to delete every `-ObjC` if it doesn't work)

**Comment by Rc85** [comment]
I skipped step 3 in the ios installation instruction and it seems to be working.
